### ISSUE TITLE
Error While Installing: "undefined exports: pit_2019"

### ISSUE THREAD

**Issue by PowellWheeler** [InStreamFisheries/PITR#1]
Hello,

I tried to install PITR today and I kept getting an error.

I'm using R version 4.0.3 on Ubuntu Linux 18.04.5 LTS x86_64. 

Thanks,

I used this code to attempt to install:

`install.packages("remotes")
remotes::install_github("InStreamFisheries/PITR")`

This is the final result:
`
Error: package or namespace load failed for ‘PITR’ in namespaceExport(ns, exports):
 undefined exports: pit_2019
Error: loading failed
Execution halted
ERROR: loading failed
removing ‘/usr/local/lib/R/site-library/PITR’
Error: Failed to install "PITR" from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp59e7HH/file2b3564195a74/PITR_1.2.0.tar.gz’ had non-zero exit status
`

**Comment by InStreamFisheries** [comment]
Hi PowellWheeler,

Thanks for identifying that bug. I forgot to remove a deleted function from the namespace. The package should load properly now. Let me know if there are other bugs; I haven't spent too much time on this in the last year so it may need some dusting off. We'd love to have more people test the functions with their data to see how the package responds and how useful it is. Let me know how it goes.

Annika

**Comment by PowellWheeler** [comment]
No problem.  Thanks for fixing it.

Some co-workers are doing a big project with PIT-tagged muskie and someone
told them about your package.  Since i'm the 'R guy' in the office they
forwarded it to me.

Hopefully, I'll get to try out your package on some real data in the
future.  I'll let you know if I have any questions.

Thanks,
Powell

**Comment by InStreamFisheries** [comment]
Great! I'll close this issue and good luck.
