### ISSUE TITLE
Data Collation Question

### ISSUE THREAD

**Issue by Vindangelo** [InStreamFisheries/PITR#2]
Hello, 

I just found this package and am excited to use it since I'm saddled with lots of PIT data from previous projects that have not been processed yet. 

I've been trying to collate raw data exported from ORRFID multi antenna HDX readers, HDX tags. I keep getting the following error, both with new and old data when trying to collate using the old_pit and new_pit functions. 

I'm not an R expert by any means so maybe there is a simple explanation here, or I'm wondering if it has to do with the format of the .txt files that I'm pointing to. I have not altered them in any way after their download from the readers. I can attach text files if needed. 

Thanks for any assistance, 

Error: Problem with `mutate()` input `reader`.
x object '.id' not found
i Input `reader` is `stringr::str_sub(.id, 1, -16)`.

**Comment by InStreamFisheries** [comment]
Hi,

Sounds like there might be an issue with your file naming convention. Are you using the format: pit_reader_mm_dd_yyyy.txt? Feel free to attach a file and I can check to see if it works on my end. PIT data are often corrupted, which can create bugs in the package. Always great to have people test it out to fill in new bug fixes.

Annika

**Comment by Vindangelo** [comment]
Hello, 

Thanks for the reply, I've attached the file. I've had the same error for multiple different files all similarly named. I've tried it with different file paths as well, one was on a network, one was on my desktop, same error. I hear you on the data corruption, you never know what you're going to get from these units. 
[mcgee_station_10_07_2016.txt](https://github.com/InStreamFisheries/PITR/files/6416377/mcgee_station_10_07_2016.txt)

**Comment by InStreamFisheries** [comment]
Hi,

I'm assuming these data are from the older reader firmware? I saved your data to a file on my desktop called Data and ran old_pit("D:/Desktop/Data"). It seemed to collate correctly. One thing to note is that sometimes your computer will assign .txt. without that string being part of the file name (which is required for PITR). Make sure that your text file contains the full file extension.

**Comment by Vindangelo** [comment]
Hi Annika,

Thanks again for your reply, I greatly appreciate your time! Yes, it's the old data style. I tried the same approach (file on desktop named "data.txt") and am still getting the same error.  I renamed the file before doing anything so the extension should be good. I've just copied my entire process here, maybe there's something else I'm doing (or not) beforehand that is leading to the error:

setwd("C:/Users/vdangelo/Desktop")
install.packages("devtools")
library(devtools)
install_github("InStreamFisheries/PITR")
library(PITR)

old<-("C:/Users/vdangelo/Desktop/data.txt") ##this works
tt<-c("900_228000079040", "982_0004046966214", "982_000404696216", "0000_0000000157501505") #this works as well
McGee<-old_pit( data = old, test_tags = tt, print_to_file = FALSE, time_zone = NULL)#error after this

##Alternatively##
old_pit( data = old, test_tags = tt, print_to_file = FALSE, time_zone = NULL)#same error
old_pit("C:/Users/vdangelo/Desktop/data.txt")#same error
McGee<-old_pit("C:/Users/vdangelo/Desktop/data.txt") #same error
#Or this, without the txt##
McGee<-old_pit("C:/Users/vdangelo/Desktop/data")#same error
old_pit("C:/Users/vdangelo/Desktop/data")#same error

Thanks very much once again, 

Vin

**Comment by InStreamFisheries** [comment]
Hi Vin,

Your file naming convention was correct before (mcgee_station_10_07_2016.txt). In your working directory, create a folder (e.g., Data) and place your text file (mcgee_station_10_07_2016.txt) within the folder. The filepath is then the path to the folder containing the data, not the data itself. The function works this way so that you can collate multiple files with only one filepath/function call.

Annika

**Comment by Vindangelo** [comment]
Worked! Thanks, simple fix. My bad.

**Comment by InStreamFisheries** [comment]
No problem and good luck with the rest of your analysis. Let me know if you have other issues.
